# Generated by Django 2.0.5 on 2018-06-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=30, verbose_name='班級名稱'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='password',
            field=models.CharField(max_length=30, verbose_name='選課密碼'),
        ),
    ]
