# Generated by Django 2.0.5 on 2018-06-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('classroom_id', models.IntegerField(default=0)),
                ('seat', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('student_id', 'classroom_id')},
        ),
    ]
