# Generated by Django 2.0.5 on 2018-06-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together=set(),
        ),
    ]
