# Generated by Django 2.0.5 on 2018-06-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180603_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.IntegerField(default=0)),
                ('student_id', models.IntegerField(default=0)),
                ('memo', models.TextField(default='')),
                ('filename', models.CharField(blank=True, max_length=250, null=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
