# Generated by Django 2.0.5 on 2018-06-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180605_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='work/', verbose_name='檔案'),
        ),
    ]
